### PR TITLE
added 'Folder' node

### PR DESCRIPTION
**Pull request by raisch**

### CODE REVIEW

**Comment by raisch** [comment]
Hm. It seems my editor reformatted everything. I'll update later today without the formatting changes.

**Comment by raisch** [comment]
Interesting that you should rename those files since, when you save a new ncft file, the `title` field is used to fill in the filename when saving. I'm also curious why you chose to change the file extension from `.json`. Do you plan on changing the output format in the future?

**Review by maximecb — COMMENTED** [review]
Generally looks good but, the rest of the codebase uses 4 spaces for tabs. Can you indent with 4 spaces as well?

**Comment by maximecb** [comment]
> Interesting that you should rename those files since, when you save a new ncft file, the `title` field is used to fill in the filename when saving. I'm also curious why you chose to change the file extension from `.json`. Do you plan on changing the output format in the future?

It's traditional to not use spaces or uppercase letters in filenames, but not as necessary nowadays.

The reason for the ncft extension is so we can differentiate with other files, but the files will remain JSON.

**Comment by raisch** [comment]
Yup. no problem.

If you'd like, I could also add an `.editorconfig` to help you maintain a
consistent coding style or you might consider adding support for `eslint`
which would allow you to do the same in a more controlled way.
--
Rob Raisch, Internet Handyman

**Comment by raisch** [comment]
cool. if you drop me an email at ***@***.***, I have other questions
that would be better addressed outside of this PR.
--
Rob Raisch, Internet Handyman

**Comment by raisch** [comment]
gack... my email is my last name at gmail.
--
Rob Raisch, Internet Handyman

**Comment by maximecb** [comment]
I just tried it and the modulated example is pretty neat.

I don't fully understand how what you've implemented maps on here:
https://ccrma.stanford.edu/~jatin/ComplexNonlinearities/Wavefolder.html

Which makes me a little hesitant. Being completely honest, one problem we face with NoiseCraft is that once we add a new type of node, people are going to depend on it, and changing said node could break people's projects. That being said, I might still just merge anyway it and ask a musician friend for feedback ;)

One question for you: would it make sense to change it so that rate == 0 means input signal is unchanged, and greater than zero applies wave folding? I'm asking because by default, the knobs range from zero to one, and the existing distortion node has value zero meaning no distortion. Is there a convention for rate values with other wave folders?

**Comment by raisch** [comment]
Maxime,

If you run the simple example, you'll note that the folded waveform
conforms to examples illustrated in many online descriptions.

If I recall my history correctly, wavefolding was an important
innovation in the Buchla series 200 model 259 Programmable Complex
Waveform Generator first made available in the 1970's, and the
algorithm in the Fold module mimics the same modulation.

That being so, I completely understand your reluctance, as I'm
constantly railing against similar issues related to NPM modules. I
have no plans to update Fold, as it performs its function as expected,
and should someone else have a better, more performant alternative,
I'd be eager to know and very open to refactoring Fold to embrace it.
However, I'm not sure how a different algorithm could be more
performant considering Fold only consumes three
one-hundred-thousandths of a second per cycle. ;)

Any such alternative would still require the same two inputs and the
one output, so it would be "plug-and-play" compatible. The only
possible "breaking change" would be how compatible any alternative
would be in terms of its harmonic characteristics. But as I understand
audio processing, there should be no difference if the alternative was
a true wavefolder.

I'm happy to scale the rate down to 0, but as you note, that would not
be conventional. From a user-experience standpoint, I see the problem
though. I'll add that tomorrow.

One thing I've been considering recently is writing documentation for
the NC modules; is this something you have planned or is "in the
works"? If so, I'm happy to help out, as either author or editor.

I also have several new modules I've been playing with, and an
improved Sine module that adds two new 'amp' (amplitude) and 'phase'
inputs which I've found useful in other synths for modulation; it is
completely "backwards compatible" since, with no sources attached, the
new module acts exactly like the original.

It occurs to me that what you have in NC could be converted so it
could host plugins. I've done this in many other projects and it would
allow your users to choose what new modules they'd need.

I note that there is also rudimentary support for "grouping" NC
modules. What is your vision for that functionality? As it exists now,
NC tends to encourage huge sprawling designs which could be better
managed through grouping multiple modules into one. I recognize the
implementation problems such a feature would present, i.e. how to
identify what inputs and outputs would be "public" on the new module,
and how to route signals within it, and how they might be somewhat
daunting. (Then again, I love a challenge. ;) )

These are some of the things I had hoped to communicate to you via direct email.

All best.

Rob.


--
Rob Raisch, Internet Handyman

**Comment by maximecb** [comment]
> I'm happy to scale the rate down to 0, but as you note, that would not
be conventional. From a user-experience standpoint, I see the problem
though. I'll add that tomorrow.

That was my main question, whether there is a convention for the minimum value to be 1. If you don't object to the minimum being zero for no modulation (no fundamental reason why it couldn't be I guess?), then let's make that change.

> These are some of the things I had hoped to communicate to you via direct email.

I'll send you an email right now to continue this discussion :)

**Comment by maximecb** [comment]
I made it so the rate starts at 0 to better match the default knob range, updated the examples, and deployed the changes.

Also shared your modulated folding example to demonstrate usage: https://noisecraft.app/931

**Comment by raisch** [comment]
wonderful. looks great. ;)

**Comment by maximecb** [comment]
Thanks for contributing it :)

**Pull request merged**
