### PR TITLE
Add SVG icons and restyle play/stop

### LINKED ISSUE #62: Colored SVG Play / Stop buttons
Right now there's a Play/Stop button in the top right corner of the app. However, it's just a text link and it's not very noticeable. That means new users often miss it and are left wondering why no audio is being produced.

I think it would make sense to have a green Play button that says "Play ▶" with the right-facing triangle next to it. This button should be replaced by a red "Stop □" button when playback is started.

The play and stop button graphics should preferably be in SVG format and should have exactly the same width and height.

### PR DESCRIPTION
**Pull request by 5Mixer**
This PR attempts to resolve #62, adding SVG icons to the play/stop button and setting them to an unchanging red/green colour.

Some decisions:
 - Icon SVG is inline.
 - To center the icon with the text, buttons are now flex contains with `align-items:center;`
 - The pure green `#0F0` is difficult to read, failing WCAG contrast ratio requirements. I've lowered it to a darker shade of green that passes. As for the red, I've left that as is for consistency with the red link buttons.
 - The icons are identically sized, but the non-monospace font caused the button to resize when clicked. I've 'fixed' this by setting a constant button width of `45pt`

Happy to revise the PR with any feedback. 🙂 

updated-play-stop

### CODE REVIEW

**Comment by maximecb** [comment]
Hello @5Mixer ! Thank you for picking up this issue :)

This looks pretty good. There's a minor issue that the text doesn't align the same in Firefox as in Chrome, it looks a bit shifted up. Do you think you could encode the Play/Stop text into the SVG instead of in the button, so that the button can look the same on Chrome and Firefox?

**Comment by 5Mixer** [comment]
Hm - is this what you're seeing? Dark browser header is firefox - sorry for the flashy GIF :slightly_smiling_face:
chrome v firefox

I had a go at encoding the text within the SVG. It's tricky to tweak constants so that the icon, text and containing box are consistent with the other navbar elements.

The result does seem to have greater cross-browser consistency, but I suspect there might be a CSS change that makes the existing PR code work - or the same result as this SVG could be achieved through setting the button height. :thinking: 

svg text comparison

The whole nav-bar may have an inconsistent height because it is dependent on the text font, which differs with the browsers default sans-serif. I can investigate further, or just try and get the text positioned correctly with SVG. :+1:

**Comment by 5Mixer** [comment]
Thanks for your patience. As far as I can tell, I don't have that issue on Firefox, or if I do, it is subtler than your screenshot. Not sure why, but it does make it difficult to fix. 😅

Latest commit is the closest I've been able to get embedding the text in SVG. How does that look for you?

**Comment by maximecb** [comment]
Thank you for your patience as well 🙏  It might be a platform difference, I'm using Firefox on macOS here 🤷‍♀️  In any case embedding the text in the SVG does seem to fix it :D

Will merge and deploy the changes. Can you also think of a way to have an on hover action for the Play and Stop buttons that would make sense and be somewhat visually consistent with the other links?

**Comment by 5Mixer** [comment]
Glad the SVG worked :slightly_smiling_face: 

Hm, visual consistency with the other buttons is tricky - they change colour because they don't have state, but the play/button can't, having state. I think it really needs the introduction of new styling across all buttons - for example text underlining, font bolding, etc. Or, more drastically, all the buttons could be restyled so that they don't change colour so dramatically on hover.

Just some random thoughts - I might be able to play around with restyling if you like, but no promises on timeline, my studies and work have ramped up. :)

**Comment by maximecb** [comment]
No problem. I'm also pretty busy with my job. It's ok for this project to move slowly :)

There's probably something to be done to improve the styling. The desire to have a green play button is because a lot of newcomers to the app seemed to not be able to figure out how to start audio playback. So it seems useful for that button to have a really distinctive look with an icon, and a green color that makes it stand out.

**Pull request merged**
