### PR TITLE
Better, anti-aliased saw and pulse oscillators with PolyBLEP

### PR DESCRIPTION
**Pull request by greg7gkb**
See info and notes in https://github.com/maximecb/noisecraft/issues/51

### CODE REVIEW

**Comment by greg7gkb** [comment]
This has not been exhaustively tested but I wanted to post it so you can hear the difference with the original impl.

Also note the issue with the square wave duty cycle parameter, which I wasn't able to resolve yet - would take more analysis and work.

**Comment by maximecb** [comment]
Thanks for putting this together Greg 🙏 

I tested this on some of the most complex patches, including
https://noisecraft.app/233

As far as I can tell using the `htop` tool, there's not much difference in CPU usage, so we're good on that front.

There's definitely a difference in the sound, but it's pretty subtle. On most patches it's actually hard to tell the difference. The old poor man's saw has more richness because of the distorted harmonics, but the PolyBLEP sounds cleaner. Both seem pretty valid and neither of them sounds bad.

Hard for me to decide what to do 😅 I feel like since we don't have a good solution for the duty cycle for the square wave, I would just keep that one the same for now, but we could merge the new sawtooth oscillator. What do you think?

**Comment by greg7gkb** [comment]
Ha! That Brazil patch is amazing - thanks for sharing.

I agree that the difference is on the subtler end but definitely there. With the Brazil patch, if you increase the octave output on some of the lower frequency MonoSeq's (e.g. bump up to E4 / A4 range) you can definitely hear a fairly big difference in the quality of the sound. But as you said, it's 'cleaner' and not necessarily 'better'.

This is a tough call!

In favor of the change:
- Cleans up osc outputs for higher frequencies, in particular things like the patch originally cited: https://noisecraft.app/103
- I want to say that bad input leads to bad output, but I really don't hear much of an issue in the patches I'm trying. Maybe someone with better ears would consider it more of a problem?

Against this change:
- Added complexity in code
- CPU hit
- Risk of new issues being introduced (this patch exposed an out-of-range exception for the new code that I'd have to look into: https://noisecraft.app/172)

You have a half-working change available now... maybe reject the PR for now and keep it around if someone really complains? 😬

**Comment by greg7gkb** [comment]
Another option: I have some colleagues who still work professionally in the space and may have some more ideas. If you'd like I can ping them.

**Comment by maximecb** [comment]
Regarding the out of range, this could be an edge case like the input frequency being 0 or less. Since anyone can connect anything to anything, you have to guard against edge cases like that.

But yeah not sure what to do. Maybe the current solution is basically good enough. This whole issue stems from a purist complaining, someone who works in the field I think, but nobody else has actually complained lol.

I pushed your code to the `polyblep` branch so at least now we have an implementation. Thanks for putting this together, and if you're looking for something else that could be fun to play with, maybe I can interest you in: https://github.com/maximecb/noisecraft/issues/81

**Comment by maximecb** [comment]
I was thinking about this, and the reason the difference is not that audible is probably that people almost always put a low pass filter after a sawtooth oscillator. It's kind of necessary because the raw sound of the sawtooth wave is not that pleasant without filtering. So the very high harmonics are almost always filtered out!

**Comment by greg7gkb** [comment]
> people almost always put a low pass filter after a sawtooth oscillator

Got it - reduces the issue even more then.

> maybe I can interest you in: #81

Definitely! I'm busy for a few days but will work on it in a week or two.

**Pull request closed without merging**
