### PR TITLE
Add support for non Chromium browsers

### LINKED ISSUE #28: Figure out why NoiseCraft doesn't work in Safari
Currently NoiseCraft doesn't produce audio output in Safari when the Play button is pressed. I haven't investigated the specific reason at all. Help would be most appreciated. If a feature is missing in Safari, we might also want to open an issue on their issue tracker.

### PR DESCRIPTION
**Pull request by chrisguttandin**
This PR uses standardized-audio-context to make NoiseCraft work in Firefox and Safari. Both browsers do currently not support any `import` statements in the code of an `AudioWorklet`. Therefore standardized-audio-context is used here to load the fallback implementation of an `AudioWorklet` which internally uses a `ScriptProcessorNode`. In that case  the code gets loaded using a regular script tag which is why `import` statements work as expected.

This PR is meant to fix #28.

### CODE REVIEW

**Comment by maximecb** [comment]
Hi Chris. Having to special case based on the user agent and then potentially import an external library on another server makes me a bit worried 😟 . I think that bundling seems more efficient, more portable and safer.

Thanks for looking into this problem and explaining what the issue was. This is much appreciated 🙏

**Comment by chrisguttandin** [comment]
No problem, this branch was not really meant to be merged like this. I just wanted to demonstrate how it could work.

I copy/pasted the user agent check which is already in use for the browser support popup. A better approach would probably be to wait for the error to happen with the native implementation before loading the fallback. This would make sure the fallback isn't used anymore once Firefox and Safari fix the bug.

**Comment by maximecb** [comment]
The thing that has me confused now is that I went ahead and I implemented the bundling on the https://noisecraft.app server, and it still only works sometimes on Safari. The first tab I open produces audio. Then, when I go to hit play on another project, no more audio :(

**Comment by chrisguttandin** [comment]
I'm believe this is a bug (but I assume Apple calls this a privacy feature) that the `AudioContext` sometimes needs to be resumed in Safari even though it was created in response to a user gesture.

I hope #64 will fix the issue.

**Pull request closed without merging**
